---
# tasks file for docker-registry

# TAG docker image with name repo
- name: docker tag
  shell: docker image tag cd-project beffa/continuous-delivery:cd-project
#push image to docker repo
- name: push image
  shell: docker push beffa/timesheet:cd-project
#Stop and remove all container
- name: remove local coantiner
  shell: docker rm $(docker ps -a -q)
#remove all local images
- name: remove local images
  shell: docker rmi -f $(docker images -aq)
