---
# tasks file for docker-registry
- name: Tag and push to docker hub
  docker_image:
    name: cd-project
    repository: beffa/continuous-delivery
    tag: beffa/continuous-delivery:cd-project
    push: yes
